### PR TITLE
updated files for react-native 0.26

### PR DESCRIPTION
**Pull request by choru-k**

### CODE REVIEW

**Comment by ajoshdee** [comment]
Hi, how can i download your build in npm?

**Comment by choru-k** [comment]
@ajoshdee yes. npm can download module from githubURL.
This is my github https://github.com/g6ling/react-native-dropdown

npm install https://github.com/g6ling/react-native-dropdown
so you can use react-native-dropdown

**Comment by ajoshdee** [comment]
Oh thanks ^^

**Comment by MaxInMoon** [comment]
possible to merge?

**Comment by gs-akhan** [comment]
I have rights to merge this, but not to publish on NPM :(

**Comment by alinz** [comment]
@gs-akhan merge it and let me know and I will publish it to npm

**Comment by jeaye** [comment]
This is still a problem, so please merge and publish the new version to npm. Thank you for the fix, @g6ling!

**Pull request closed without merging**
