### PR TITLE
Allow passing a value to Option

### PR DESCRIPTION
**Pull request by alfondotnet**

### CODE REVIEW

**Comment by gs-akhan** [comment]
+1

**Comment by agmcleod** [comment]
Was looking through the code, surprised this isn't already an option. +1

**Comment by gs-akhan** [comment]
@alinz  Hi .. can we merge this ? .. thanks

**Comment by gs-akhan** [comment]
@alfonsoperez 
Hi. Can u please commit this here https://github.com/gs-akhan/react-native-dropdown
as well. I will be maintaining this  actively  adding animations and bug fixes actively here 
Thanks

**Comment by alinz** [comment]
I will merge this code into the repo
@gs-akhan I have overwhelmed by a lot of react-native components which I have to maintain. Sorry if I don't get back to you. If you are willing to help I will make you contributor for this project. Let me know. 

@alfonsoperez thanks for this.

**Comment by gs-akhan** [comment]
@alinz I am ready offer all I could. I use this into one of our project too. Please add me as contributor.

Thanks.

**Comment by gs-akhan** [comment]
I will also add docs on readme, howtos.  :+1:

**Comment by alinz** [comment]
@gs-akhan you are in! use `git flow` for versioning.

**Pull request merged**
